/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef CUSTOMURLHANDLER_AUTODEFS_H
#define CUSTOMURLHANDLER_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_CUSTOMURLHANDLER_NAME "CustomURLHandler"
#define S3E_EXT_CUSTOMURLHANDLER_HASH 0x40d7e8d1

#endif /* !CUSTOMURLHANDLER_AUTODEFS_H */
